[package]
name = "semify"
description = "Add semicolons to Python code."
version = "0.1.0"
edition = "2021"
authors = ["interrrp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
